name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  GCP_PROJECT: helical-loop-453001-c0
  GKE_CLUSTER: air-quality-cluster
  GKE_ZONE: europe-central2-a

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            gcr.io/${{ env.GCP_PROJECT }}/frontend:latest
            gcr.io/${{ env.GCP_PROJECT }}/frontend:${{ github.sha }}

      - name: Configure GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ env.GCP_PROJECT }}

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/
